export const AuthConstants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_RESET: "LOGIN_RESET_DATA",
};

export const USERTYPES = {
  USER_ERROR: "USER_ERROR",
  USER_LOADING: "USER_LOADING",
  USER_RESET: "USER_RESET",
  USER_DATA: "USER_DATA",
};

export const TOKEN = {
  USER_TOKEN: "USER_TOKEN",
  USER_TOKEN_RESET: "USER_TOKEN_RESET",
};
